/**
 * The Drizzle/SQLite database handle. FlowState is local-first: all structured
 * state (workspaces, Claude transcripts, settings) lives in a single SQLite file
 * at `app.getPath('userData')/flowstate.db`. Secrets are kept in the OS Keychain
 * via safeStorage (see `secrets.ts`) — only their ciphertext is stored here.
 *
 * Migrations are the SQL files generated by drizzle-kit into `apps/main/drizzle/`
 * and applied on open. That folder ships beside the app: in dev it sits next to
 * the app's package.json (`app.getAppPath()`); when packaged it's copied into
 * Resources via electron-builder `extraResources` (`process.resourcesPath`).
 */
import { join } from 'node:path';
import Database from 'better-sqlite3';
import { type BetterSQLite3Database, drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { app } from 'electron';
import * as schema from './schema';

///////////
// Types //
///////////

type Db = BetterSQLite3Database<typeof schema>;

/////////////
// Helpers //
/////////////

// Module-level handles; populated by openDb() and cleared by closeDb().
let sqlite: Database.Database | null = null;
let db: Db | null = null;

function migrationsFolder(): string {
  return app.isPackaged
    ? join(process.resourcesPath, 'drizzle')
    : join(app.getAppPath(), 'drizzle');
}

/** Open the database (idempotent) and apply any pending migrations. */
export function openDb(): Db {
  if (db) return db;
  const file = join(app.getPath('userData'), 'flowstate.db');
  sqlite = new Database(file);
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  db = drizzle(sqlite, { schema });
  migrate(db, { migrationsFolder: migrationsFolder() });
  return db;
}

/** The open Drizzle handle. Throws if the store has not been initialized. */
export function getDb(): Db {
  if (!db) {
    throw new Error('Store not initialized — call initStore() before accessing the database.');
  }
  return db;
}

/** Close the database (called on app quit). */
export function closeDb(): void {
  if (sqlite) {
    sqlite.close();
    sqlite = null;
    db = null;
  }
}
